"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let nullVariable = null;
console.log(nullVariable);
console.log(typeof nullVariable);
let UndefinedVariable;
console.log(UndefinedVariable);
console.log(typeof UndefinedVariable);
console.log(`exemplo 1: ${nullVariable == UndefinedVariable}`);
console.log(`exemplo 1: ${nullVariable === UndefinedVariable}`);
